# https://taskfile.dev

version: '3'

vars:
  DOCKER_USERNAME: yolowingpixie
  CONTAINER_NAME: devcontainer
  DEPS: [yq]

tasks:
  default:
    cmds:
      - task: build
      - task: docker:tag:dev-latest
      - task: run

  build:
    desc: "Build image"
    aliases: [docker:build]
    silent: true
    cmds:
      - |
        docker build \
          --build-arg UBUNTU_VERSION=$(yq -r .base.ubuntu config.yaml) \
          -t {{.CONTAINER_NAME}} \
          .
  run:
    desc: "Run container with Docker socket mounted (platform-specific)"
    aliases: [docker:run]
    cmds:
      - task: run:{{OS}}

  run:darwin:
    internal: true
    desc: "Run container on macOS"
    platforms: [darwin]
    silent: true
    cmds:
      - docker run -it -v /var/run/docker.sock:/var/run/docker.sock {{.CONTAINER_NAME}}

  run:windows:
    internal: true
    desc: "Run container on Windows (Docker Desktop)"
    platforms: [windows]
    silent: true
    cmds:
      - docker run -it --privileged -v //var/run/docker.sock:/var/run/docker.sock {{.CONTAINER_NAME}}

  docker:tag:dev-latest:
    desc: "Tag image"
    silent: true
    cmds:
      - docker tag {{.CONTAINER_NAME}} {{.DOCKER_USERNAME}}/{{.CONTAINER_NAME}}:dev-latest

  docker:push:
    desc: "Push image"
    silent: true
    cmds:
      - docker push {{.DOCKER_USERNAME}}/{{.CONTAINER_NAME}}

  stop:
    silent: true
    cmds:
      - docker stop {{.CONTAINER_NAME}}

  setup:
    desc: "Setup missing dependencies via appropriate package manager for each platform"
    cmds:
      - task: setup:{{OS}}

  setup:windows:
    internal: true
    platforms: [windows]
    cmds:
      - task: ensure-scoop
      - for: {var: DEPS}
        task: install-if-missing:windows
        vars:
          PACKAGE: '{{.ITEM}}'

  setup:darwin:
    internal: true
    platforms: [darwin]
    cmds:
      - task: ensure-brew
      - for: {var: DEPS}
        task: install-if-missing:darwin
        vars:
          PACKAGE: '{{.ITEM}}'

  install-if-missing:darwin:
    internal: true
    platforms: [darwin]
    label: 'install-{{.PACKAGE}}'
    status:
      - which {{.PACKAGE}}
    cmds:
      - echo "Installing {{.PACKAGE}} via brew..."
      - brew install {{.PACKAGE}}

  install-if-missing:windows:
    internal: true
    platforms: [windows]
    label: 'install-{{.PACKAGE}}'
    status:
      - Get-Command {{.PACKAGE}}
    cmds:
      - echo "Installing {{.PACKAGE}} via scoop..."
      - scoop install {{.PACKAGE}}

  ensure-scoop:
    internal: true
    platforms: [windows]
    status:
      - scoop --version
    cmds:
      - echo "Installing scoop..."
      - Invoke-WebRequest -UseBasicParsing get.scoop.sh | Invoke-Expression
      - scoop update

  ensure-brew:
    internal: true
    platforms: [darwin]
    status:
      - brew --version
    cmds:
      - echo "Installing brew..."
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - brew update