# https://taskfile.dev

version: '3'

vars:
  CONTAINER_NAME: devcontainer

tasks:
  default: [build, run]
  build:
    cmds:
      - docker build -t {{.CONTAINER_NAME}} .
    silent: true
  run:
    cmds:
      - docker run -it {{.CONTAINER_NAME}}
    silent: true
  stop:
    cmds:
      - docker stop {{.CONTAINER_NAME}}
    silent: true
