# Kubectl
alias k='kubectl'
alias klog='kubectl logs -f'
alias kg='kubectl get'
alias kd='kubectl describe'
alias kdp='kubectl describe pod'
alias kdns='kubectl describe namespace'
alias kdsa='kubectl describe serviceaccount'
alias kdn='kubectl describe node'
alias kds='kubectl describe service'
alias kdi='kubectl describe ingress'
alias kdsec='kubectl describe secret'
alias kdconfimap='kubectl describe configmap'
alias kdnode='kubectl describe node'
alias kdpod='kubectl describe pod'

# Terraform
alias tf='terraform'
alias tfa='terraform apply'
alias tfp='terraform plan'
alias tfv='terraform validate'

# Git
alias g='git'

# Helm
alias h='helm'
alias hls='helm ls'
alias hdep='helm dependency'
alias hget='helm get'
alias hstatus='helm status'
alias hupgrade='helm upgrade'
alias hrollback='helm rollback'
alias hhistory='helm history'
alias hdiff='helm diff'
alias htemplate='helm template'
alias hlint='helm lint'
alias htest='helm test'
alias hverify='helm verify'
alias hinstall='helm install'

# Docker
alias d='docker'
alias dlog='docker logs -f'
alias dps='docker ps'
alias dstop='docker stop'
alias drm='docker rm'
alias drmi='docker rmi'
alias dbuild='docker build'
alias dpush='docker push'
alias dpull='docker pull'
alias dtag='docker tag'
alias dlogin='docker login'
alias dlogout='docker logout'
alias drun='docker run -it'